apiVersion: v1
kind: Namespace
metadata:
  name: demo-namespace

---

# Deployment v1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app-v1
  namespace: demo-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-app
      version: v1
  template:
    metadata:
      labels:
        app: spring-boot-app
        version: v1
    spec:
      containers:
        - name: spring-boot-app-v1
          image: demo-app-v1:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

---

# Ãšnico Service compartilhado
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-service
  namespace: demo-namespace
spec:
  selector:
    app: spring-boot-app  # label comum aos dois deployments
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080

---

# Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spring-boot-ingress
  namespace: demo-namespace
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /system-v1
            pathType: Prefix
            backend:
              service:
                name: spring-boot-service
                port:
                  number: 80
          - path: /system-v2
            pathType: Prefix
            backend:
              service:
                name: spring-boot-service
                port:
                  number: 80